/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alxs1' at '12/05/17 19:42' with Gradle 2.14.1
 *
 * @author alxs1, @date 12/05/17 19:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
